#ifndef DEFAULTPICMANFIGURE_GLOBAL_H
#define DEFAULTPICMANFIGURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEFAULTPICMANFIGURE_LIBRARY)
#  define DEFAULTPICMANFIGURE_EXPORT Q_DECL_EXPORT
#else
#  define DEFAULTPICMANFIGURE_EXPORT Q_DECL_IMPORT
#endif

#endif // DEFAULTPICMANFIGURE_GLOBAL_H
