[package]
name = "lab_8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
imageproc = "0.23.0"
rustfft = "4.1.0"
ndarray = "0.15"
num-traits = "0.2.17"
num-complex = "0.4.4"
