#ifndef RIGHTTRIANGLE_GLOBAL_H
#define RIGHTTRIANGLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RIGHTTRIANGLE_LIBRARY)
#  define RIGHTTRIANGLE_EXPORT Q_DECL_EXPORT
#else
#  define RIGHTTRIANGLE_EXPORT Q_DECL_IMPORT
#endif

#endif // RIGHTTRIANGLE_GLOBAL_H
