[package]
name = "lab_7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jubjub = "0.9.0"
rand = "0.8.5"
rand_core = "0.6.4"
num-bigint = "0.4"
serde_json = "1.0.108"
hex = "0.4.3"
num = "0.4.1"
